# Generated by Django 5.0 on 2024-01-16 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Время рассылки')),
                ('status', models.CharField(blank=True, choices=[(True, 'Успешно'), (False, 'Неудача')], default=False, max_length=10, null=True, verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Лог сообщения',
                'verbose_name_plural': 'Логи сообщений',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Рассылка')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки')),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая рассылка')),
                ('end_date', models.DateTimeField(verbose_name='Конец рассылки')),
                ('interval', models.CharField(choices=[('once', 'разовая'), ('daily', 'ежедневно'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], default='Once', max_length=10, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('active', 'Запущена'), ('finished', 'Завершена')], max_length=10, verbose_name='Статус')),
                ('is_activated', models.BooleanField(choices=[(True, 'Активна'), (False, 'Неактивна')], default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('start_date',),
                'permissions': [('set_is_activated', 'Может отключать рассылку')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
