# Generated by Django 5.0 on 2024-01-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_client_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('client_delete', 'Может удалять клиентов')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('start_date',), 'permissions': [('set_is_activated', 'Может отключать рассылку'), ('can_view', 'Может просматривать рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
